import Head from 'next/head';
import AdminPage from '@/modules/pagesComponents/AdminPage';
import withAuth from '@/modules/auth/withAuth';

function Admin() {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminPage />
    </>
  );
}

export default withAuth(Admin, ['superadmin']);
