import Head from 'next/head';
import withAuth from '@/modules/auth/withAuth';
import WebSocketListener from '@/commons/web';
import MainPage from '../modules/pagesComponents/MainPage';

function Home() {
  WebSocketListener();
  return (
    <>
      <Head>
        <title>Maps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage />
    </>
  );
}

export default withAuth(Home, ['admin', 'superadmin']);
